[package]
name = "rune"
version = "0.1.0"
authors = ["Steffen Haug <steffen@haug.rs>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
